// [emoji, search keywords (20+ per emoji)] — 220 most common/useful
export const EMOJI_PICKER_SET: [string, string][] = [
  // Smileys & emotion
  ['😀','happy smile grin cheerful joy face glad positive mood friendly beam radiant sunny upbeat pleased delighted merry joyful lighthearted bright'],
  ['😊','smile blush happy warm kind gentle pleased soft sweet content gracious tender heartfelt lovely appreciative humble cozy mellow soothing serene'],
  ['😂','laugh cry funny joy hilarious tears humor lol rofl comedy joke witty giggle hysterical amused cracking dying priceless ridiculous absurd'],
  ['🥲','tear smile grateful bittersweet touched moved emotional proud nostalgia sentimental poignant wistful tender heartfelt relieved overwhelmed sincere raw humble deep'],
  ['😍','heart eyes love adore crush smitten romance infatuated affection desire obsessed gorgeous beautiful attraction swoon stunning captivated mesmerized charmed fond'],
  ['🤩','star eyes excited amazed wow awesome thrilled dazzled impressed wonderful starstruck spectacular astonished admire fabulous incredible magnificent blown-away marvelous'],
  ['😎','cool sunglasses chill confident swagger smooth boss relaxed suave laid-back casual badass stylish composed unfazed nonchalant effortless slick sharp poised'],
  ['🤔','thinking hmm wondering ponder curious consider question reflect contemplate uncertain puzzled deliberate evaluate analyze skeptical doubtful mull examine weigh speculate'],
  ['😅','sweat nervous laugh awkward oops relief uncomfortable embarrassed tense uneasy sheepish cringe clumsy mistake blunder flustered self-conscious wince strained'],
  ['😢','cry sad tear upset weep sorrow grief heartbreak melancholy dejected mournful gloomy downcast depressed dismal hurt anguish pain morose lonely'],
  ['😤','angry huff frustrated mad annoyed furious rage irritated steam vent livid pissed irate seething hostile bitter aggravated fuming enraged grumpy'],
  ['🥳','party celebrate birthday confetti festive hooray cheers congratulations bash jubilant revelry toast fiesta gala carnival merrymaking rejoice triumph occasion carnival'],
  ['😴','sleep tired zzz rest nap drowsy snore exhausted bedtime dream doze slumber fatigue weary drained knocked-out unconscious peaceful lullaby recharge'],
  ['🤯','mind blown explode shock amazed unbelievable crazy insane astonished stunned flabbergasted gobsmacked revelation epiphany incredible speechless overwhelmed shook bewildered startled'],
  ['🫡','salute respect honor duty serve acknowledge formal military tribute obey discipline officer rank attention report comply loyal patriotic ceremony allegiance'],
  ['🫠','melting face relax dissolve hot overwhelmed sinking droopy fading soft warm liquid puddle embarrassed shy uncomfortable bashful heat surrender yield'],
  ['😇','halo angel innocent pure good blessed holy kind sweet divine virtuous righteous saintly wholesome moral gracious sincere noble charitable devout values integrity'],
  ['🤗','hug open arms warm embrace friendly welcoming cuddle comfort caring affection squeeze support reassure tender closeness nurture hold shelter soothe'],
  ['🥺','pleading puppy eyes cute beg adorable sad sweet hopeful tender vulnerable earnest innocent desperate longing helpless sympathetic needy wistful pitiful'],
  ['😏','smirk sly sneaky mischievous cocky flirty knowing cheeky devious suggestive cunning wily crafty scheming playful teasing provocative naughty witty sardonic'],
  // People & gestures
  ['👋','wave hello bye greet farewell welcome hand gesture hi howdy salute morning evening introduction meet departure arrive friendly acknowledge hail'],
  ['👍','thumbs up good ok approve agree yes like correct positive nice affirm endorse validate confirm accept support praise recommend solid fine'],
  ['👎','thumbs down bad dislike disagree disapprove reject no wrong negative fail oppose deny veto decline refuse condemn criticize poor unsatisfactory'],
  ['✌','victory peace sign two win triumph freedom success hand gesture symbol harmony accord truce ceasefire unity solidarity pact alliance double'],
  ['🤝','handshake deal agree partnership cooperation trust alliance meet business contract negotiate collaborate unite pact mutual bond formal settle welcome greet'],
  ['🙏','pray thanks please beg hope grateful faith worship request mercy namaste appreciate blessing reverence devotion plead humble sincere spiritual bow'],
  ['💪','muscle strong flex power strength gym workout fitness bicep tough mighty robust endurance athletic vigor stamina resilient capable force iron motivation motivate determination perseverance grit willpower drive hustle'],
  ['👁','eye watch see look observe view gaze stare vision focus monitor witness scan survey inspect peek glimpse perceive detect notice'],
  ['🧠','brain mind think smart intelligent idea genius memory knowledge wisdom logic reason cognitive mental intellect insight clever strategy analysis process second-brain PKM zettelkasten obsidian note-taking knowledge-management productivity'],
  ['❤','heart love red passion romance care affection warmth valentine devotion adore cherish bond emotion feeling deep intimate tender compassion soul'],
  ['🧡','orange heart warm autumn friendly creative energy enthusiasm vibrant playful bold spirited dynamic active lively zest courage adventurous generous vivid'],
  ['💛','yellow heart bright sunshine happiness friendship optimism gold warm cheerful radiant glowing positive uplifting grateful sunny jolly gleeful beaming mellow'],
  ['💚','green heart nature growth health lucky harmony eco fresh organic renewal vitality balance wellness prosperity earth botanical flourish fertile healing'],
  ['💙','blue heart calm trust loyalty peace sky ocean serene cool steady reliable sincere depth tranquil honest faithful true dependable stable'],
  ['💜','purple heart royal creative mystic spiritual elegant luxury wisdom magic noble regal dreamy enchanting artistic mysterious imaginative fantasy cosmic divine'],
  ['🖤','black heart dark emo gothic strength power elegant solid formal edgy mysterious deep intense dramatic bold sleek sharp modern fierce'],
  ['🤍','white heart pure clean innocent simple minimal blank pale clarity transparent pristine fresh light serene peaceful honest plain delicate airy'],
  ['🩷','pink heart cute sweet soft blush feminine gentle tender lovely romantic charming adorable pastel warm delicate graceful youthful dreamy pretty'],
  ['👀','eyes look watch stare peek curious observe glance spy attention gaze scan notice perceive scrutinize inspect survey witness sneak vigilant'],
  ['🫶','heart hands love care support appreciate cherish grateful adore affection embrace nurture compassion tenderness kindness warmth devotion protect hold treasure'],
  ['👏','clap applause bravo congratulations well done praise celebrate cheer ovation encore standing recognition honor tribute commend salute kudos respect hail'],
  ['🤞','fingers crossed luck hope wish fortune faith prayer promise desire optimism chance gamble bet superstition blessing favorable outcome trust believe'],
  ['✍','writing hand author compose draft pen pencil scribe letter note journal diary manuscript essay creative literary blog prose story editorial note-taking daily'],
  ['🦾','mechanical arm prosthetic robot strong bionic power tech future cyborg augmented enhanced titanium steel advanced upgrade superhuman iron grip force'],
  // Nature
  ['🌱','seedling sprout grow plant garden green fresh new beginning growth nurture cultivate develop emerge start tender young bud shoot germinate motivation habit progress self-improvement'],
  ['🌿','herb leaf green nature botanical plant garden organic fresh foliage verdant lush tropical fern frond branch stem flora vegetation herbal'],
  ['🍀','clover luck lucky fortune shamrock irish four leaf charm green blessing chance auspicious favorable prosperity serendipity fate destiny talisman wish'],
  ['🌸','blossom flower pink cherry spring japan sakura bloom petal delicate fragile beauty grace renewal feminine elegant transient fleeting gentle soft'],
  ['🌺','flower hibiscus tropical bloom garden colorful blossom Hawaii red petal exotic warm paradise island vibrant lush gorgeous decorative ornamental vivid'],
  ['🌻','sunflower bright yellow sun summer garden happy cheerful bloom warm golden tall field radiant joyful optimistic sunny vibrant tall rustic'],
  ['🍂','autumn fall leaf season brown orange harvest change dry maple deciduous crisp golden rustic nostalgic wind fading transitional November cool'],
  ['🌊','wave ocean water sea surf tide beach coast marine splash current deep blue shore nautical aqua tropical flow crash ripple'],
  ['🔥','fire flame hot burn heat lit trending popular blazing passion fierce intense energy wild warm glow ember ignite blaze fury motivation drive determination hustle'],
  ['❄','snowflake cold ice winter frozen frost chill freeze crystal snow unique delicate white pure arctic icy glacial blizzard pristine flurry'],
  ['⚡','lightning bolt energy power electric thunder fast speed charge shock voltage surge zap current intensity storm flash strike dynamic quick'],
  ['🌈','rainbow colors spectrum hope promise diversity pride arch weather sky after-rain bridge multicolor vivid bright beautiful magical optimistic harmony dream'],
  ['☀','sun sunny bright day warm light summer morning golden clear radiant dawn daylight sunshine noon tropical glow beaming cheerful heat'],
  ['🌙','moon night crescent dark sky evening sleep lunar celestial twilight midnight dream nocturnal dusk starlit calm quiet serene mysterious glow'],
  ['⭐','star favorite rated best top quality night sky shining bright golden award featured highlight bookmark special important premium excellent notable motivation inspiration aspiration goal'],
  ['🌟','glowing star shine brilliant sparkle twinkle radiant celestial bright excellent dazzling luminous stellar magnificent outstanding remarkable superb impressive splendid glistening'],
  ['✨','sparkles shine magic glitter glamour special clean new fresh dazzle enchant fairy dust twinkling glowing radiant premium polished fancy luxury'],
  ['🏔','mountain peak summit high adventure nature hike climb snow alpine majestic rugged wilderness terrain elevation scenic vast panoramic ridge remote'],
  ['🌍','earth globe world planet geography international travel map continent environment global humanity civilization ecosystem biosphere terra homeland ground soil terrain'],
  ['🌐','globe internet web network worldwide connected online digital global browser worldwide domain website cyberspace virtual cloud server protocol communication data'],
  ['🪴','potted plant house indoor green decor home garden succulent grow ceramic shelf desk room windowsill cozy nurture botanical houseplant living'],
  ['🌲','evergreen tree pine forest nature wood christmas conifer green tall spruce fir woodland timber grove shade canopy wilderness wild dense'],
  ['🍄','mushroom fungus forest nature wild toadstool organic earthy woodland magic mycelium cap stem spore edible forage ground damp mysterious fairy'],
  ['🐝','bee honey buzz insect pollinate hive sting yellow worker busy queen colony flower nectar wax sweet industrious diligent swarm spring'],
  ['🦋','butterfly insect nature beautiful transform wings colorful metamorphosis garden flutter cocoon caterpillar chrysalis elegant graceful delicate pattern migrate spring change'],
  ['🐾','paw prints animal pet footprint track dog cat walk trail path follow clue trace mark step wild forest ground muddy'],
  ['🐱','cat kitten pet feline meow cute furry animal whiskers playful independent curious agile pounce purr cuddly fluffy lazy graceful clever'],
  ['🐶','dog puppy pet canine bark loyal cute furry animal friend faithful companion fetch walk leash tail wag obedient loving playful'],
  ['🐦','bird tweet chirp fly wing feather animal nature sky perch nest song sparrow finch robin bluebird avian beak flock'],
  ['🦅','eagle bird raptor fly soar majestic predator wing sky freedom hunt prey powerful wild nature hawk falcon talons bald'],
  ['🐧','penguin bird cold ice arctic antarctic animal cute waddle tuxedo swim fish emperor colony winter flightless snow south pole'],
  ['🦉','owl bird night wise nocturnal hoot wisdom animal forest eye feather silent hunt branch tree mysterious clever nature perch'],
  ['🦜','parrot bird colorful tropical talk mimic pet feather fly beak wing exotic jungle rainforest perch smart pirate macaw cockatoo'],
  ['🕊️','dove bird peace white fly gentle wing olive branch freedom hope calm pure spirit symbol nature pigeon harmony love'],
  // Food & objects
  ['☕','coffee tea hot drink cup morning cafe latte espresso brew cappuccino java bean roast aroma cafeteria steam warm cozy mocha'],
  ['🍵','tea cup hot drink matcha green herbal warm sip beverage chamomile jasmine oolong steep kettle ceremony calming soothing refreshing zen'],
  ['🍺','beer drink pub bar cheers alcohol lager ale mug cold draft brew hops craft stout pint toast social friday weekend'],
  ['🍎','apple fruit red healthy food snack organic teacher crisp fresh juicy sweet autumn harvest orchard pie cider nutrition diet natural'],
  ['🍋','lemon yellow sour citrus fresh juice zest tart tangy squeeze vitamin acidic bright peel slice garnish refreshing sharp summery clean'],
  ['🎂','cake birthday celebration dessert sweet party frosting candle treat slice chocolate vanilla cream layers festive anniversary surprise bake decorate wish'],
  ['🍕','pizza food slice italian cheese pepperoni dinner lunch meal party takeout delivery crust topping oven bake supreme margherita sausage bacon'],
  ['🍷','wine glass drink red white elegant dinner celebration grape toast vineyard vintage merlot chardonnay sommelier decant pair swirl bouquet cellar'],
  ['🧁','cupcake sweet dessert treat frosting bake mini cake sprinkles sugar icing butter cream vanilla chocolate flavor decorative pretty snack party'],
  ['🥑','avocado healthy green food guacamole fresh organic toast salad superfood nutrition fat creamy ripe pit skin millennial trendy bowl spread'],
  // Activities & sports
  ['🎯','target bullseye goal aim focus precision objective hit center shoot accuracy direct purpose mission intent strategy plan mark dart exact motivation project-management OKR productivity'],
  ['🏆','trophy award win champion success prize competition gold medal achieve glory honor excellence triumph recognition accomplishment victorious reward outstanding superior motivation milestone'],
  ['🥇','medal gold first winner champion award best victory prize compete podium top achievement record excellence olympic performance elite leading outstanding'],
  ['🎮','game controller play video console gaming joystick fun arcade entertain pixel level score quest adventure retro online multiplayer stream hobby'],
  ['🎨','art palette creative paint colors draw design brush canvas studio illustration sketch masterpiece gallery museum expression visual aesthetic craft talent'],
  ['🎵','music note song melody tune sound rhythm beat listen audio harmony instrument compose lyric chorus verse album record concert band'],
  ['🎬','clapper film movie cinema director action scene video cut shoot production camera reel premiere screenplay actor studio Hollywood blockbuster edit'],
  ['📷','camera photo picture snap capture image shoot lens portrait memory digital photography focus exposure frame album gallery angle composition shot'],
  ['🎁','gift present box surprise birthday wrap holiday bow giving package reward treat donation offering favor gesture generous festive occasion token'],
  ['🎲','dice game random roll chance luck board casino gamble play probability bet wager odds risk fortune unpredictable tabletop strategy number'],
  ['🧩','puzzle piece solve jigsaw fit connect challenge logic brain together assemble pattern match complete figure-out mystery riddle clue problem think project management planning'],
  ['🎭','theater masks drama comedy tragedy acting perform stage show play musical opera scene character role audience curtain spotlight expression emotion'],
  ['🏃','running exercise fitness jog sprint athlete sport race training track marathon cardio endurance speed stride dash pace outdoor health hustle'],
  ['🧘','yoga meditation calm relax zen mindful stretch balance pose peace breathe serenity harmony wellness chakra flexibility inner tranquil centered holistic'],
  ['🎸','guitar music rock instrument band play strings chord acoustic electric solo riff strum amplifier concert jam blues country folk melody'],
  ['🎤','microphone sing voice karaoke record perform speak audio vocal stage broadcast interview podcast announce present host emcee lecture debate speech'],
  ['🎧','headphones music listen audio sound beats wireless over-ear podcast stereo noise-cancel bass volume immersive studio DJ mix focus zone'],
  // Travel & places
  ['🚀','rocket launch space shuttle blast explore mission fast speed orbit astronaut cosmos NASA thrust propulsion countdown takeoff interstellar voyage frontier motivation ambition productivity goal'],
  ['✈','airplane travel fly flight jet trip journey airline departure sky arrival boarding runway pilot altitude cruise vacation abroad international route'],
  ['🚂','train travel rail transport commute locomotive station track journey ride railway express schedule platform conductor engine carriage steam bullet subway'],
  ['🏠','house home building family residence living shelter comfort cozy dwelling roof neighborhood street property estate domestic abode sanctuary warm safe'],
  ['🏙','city building skyline urban downtown skyscraper metro architecture towers busy modern concrete landscape panorama dense cosmopolitan hub infrastructure commercial scenic'],
  ['🌆','city sunset evening skyline dusk twilight urban golden horizon vista panorama silhouette beautiful glow orange scenic view rooftop calm peaceful'],
  ['🗼','tower landmark tokyo tall structure monument observation antenna tourist famous iconic viewpoint skyline spire beacon height architecture symbol famous historic'],
  ['🏖','beach vacation holiday sand sun relax coast tropical resort shore umbrella palm waves swim seaside paradise island getaway summer lounge'],
  ['⛺','tent camping outdoor adventure nature camp hike shelter wilderness trek bonfire campfire forest park survival explore backpack gear stargazing trail'],
  // Objects & tools
  ['📁','folder directory organize files storage category archive system group contain collection structure project classify manage sort browse navigate hierarchy digital'],
  ['📂','open folder browse directory files explore access documents content view expand reveal display inside contents read inspect review navigate show'],
  ['📄','document page file text paper sheet blank note report form letter article template draft record manuscript proof printout copy format'],
  ['📝','memo write note edit pencil draft compose jot pad paper journal entry log record reminder agenda minutes summary outline plan note-taking productivity PKM obsidian daily'],
  ['📋','clipboard copy paste checklist list tasks form survey record data inventory register questionnaire roster tally schedule template assessment evaluation audit project management kanban workflow productivity'],
  ['📓','notebook journal diary daily log planner note-taking writing personal reflection thoughts record entry ledger memo pad book cover bound ruled'],
  ['📒','ledger notebook yellow note-taking planner log record register journal study workbook pad bound memo daily agenda handbook reference catalog list'],
  ['🗒','notepad spiral memo notes jot scratch paper quick draft scribble bullet list to-do reminder write pad tear-off log lined daily'],
  ['📌','pushpin pin tack mark attach fixed bulletin board location hold sticky notice important remember highlight anchor secure fasten point flag'],
  ['📍','location pin map marker place navigate address point destination drop waypoint coordinate GPS venue spot position site area zone district'],
  ['🔖','bookmark save mark tag favorite label chapter placeholder remember keep flag reference highlight annotate note index tab quick-access return later'],
  ['🗂','index dividers tabs organize sort category section file cabinet group partition separate classify arrange order divide folder structure system manage second-brain PKM knowledge-base taxonomy'],
  ['📅','calendar date schedule plan event day month year appointment agenda booking diary timeline deadline milestone reminder period term session slot project management planner productivity'],
  ['🗓','calendar spiral planner monthly schedule organize dates agenda timeline view weekly annual overview layout display wall desk flip page log'],
  ['⏰','alarm clock time wake morning schedule reminder urgent prompt early ring buzzer alert snooze set punctual deadline appointment routine daily'],
  ['🕐','clock time hour watch schedule deadline countdown moment period tick minute second duration interval elapsed timing pace tempo rate meter'],
  ['⏱','stopwatch timer speed race countdown track measure performance seconds lap interval benchmark timing record split pace precision accurate athletic test'],
  ['📊','chart bar data statistics graph analytics metrics report visual compare dashboard insight trend analysis benchmark KPI measure performance overview summary project management productivity'],
  ['📈','chart up growth trend increase rise profit improve progress gain ascend upward boost expand rally surge climb advance momentum positive'],
  ['📉','chart down decline fall drop decrease loss reduce crash lower slump downturn plunge shrink sink dip recession regression negative slide'],
  ['💡','idea light bulb insight inspiration bright creative solution innovation tip eureka invention brainstorm thought concept suggestion proposal spark clever genius motivation productivity'],
  ['🔍','search magnify zoom find discover look investigate inspect explore detail examine research scan probe review query filter analyze locate trace'],
  ['🔗','link chain url connect web hyperlink attach join bond reference anchor association coupling bridge path redirect route endpoint integration share PKM backlink graph relationship note'],
  ['📢','loudspeaker announce broadcast megaphone alert proclamation notify shout public news declaration publicity promote marketing campaign event rally spread amplify voice'],
  ['🔔','bell notification alert ring alarm remind chime ding attention sound signal update notice ping subscribe follow incoming event trigger wake'],
  ['💬','speech bubble chat message talk communicate discuss conversation text dialog comment reply respond thread forum discourse exchange interact social feedback'],
  ['💭','thought think bubble idea ponder dream imagine reflect wonder muse daydream consider fantasy vision concept brainstorm mind inner silent deep'],
  ['📚','books study library read learn education knowledge stack collection reference textbook academic literature shelf volume encyclopedia resource material course school reading-list second-brain'],
  ['📖','open book read learn study page text knowledge literature chapter story novel tale passage essay content information lesson guide manual journal diary reading daily log'],
  ['📜','scroll document ancient paper certificate decree parchment history old formal diploma charter proclamation manuscript edict torah scripture archive relic legacy'],
  ['✉','envelope email letter mail postal message inbox correspondence send post stamp seal deliver package address formal invitation announcement card greetings'],
  ['📧','email message digital mail compose inbox outbox electronic send receive newsletter subscribe forward reply thread attachment draft spam filter contact'],
  ['📥','inbox download receive import collect arrive gather incoming tray message queue pending unread new items deliveries submissions requests notifications feed'],
  ['📤','outbox upload send export share publish dispatch deliver release submit broadcast distribute deploy push outgoing transfer transmit post forward ship'],
  ['🗑','trash delete remove waste garbage bin discard throw dispose recycle junk refuse clean purge erase eliminate dump clear sweep void'],
  ['📐','triangle ruler geometry math angle measure draft technical precision shape protractor degree architect blueprint engineer design schematic plan layout grid'],
  ['🧲','magnet attract pull force iron metal charge stick pole draw repel field north south lodestone flux ferrite neodymium hold grip'],
  ['💊','pill medicine health pharmacy drug capsule vitamin dose cure treatment prescription supplement tablet remedy healing therapy antibiotic painkiller relief wellness'],
  ['🩺','stethoscope doctor health medical exam checkup hospital clinical care heart listen diagnosis nurse physician practitioner consultation vital signs blood pressure'],
  ['🪞','mirror reflection look glass vanity self image surface shine check inspect reverse symmetry double copy gaze appearance face beauty truth'],
  ['🧸','teddy bear toy cute stuffed plush child soft comfort cuddly huggable sweet innocent play nursery gift cozy warm friend hug'],
  // Tech
  ['💻','laptop computer code program work device screen technology notebook portable developer software engineer terminal ide workspace remote digital keyboard typing'],
  ['🖥','desktop monitor screen display computer workstation setup office technology pc tower dual ultrawide resolution pixel panel gaming workspace professional edit'],
  ['📱','phone mobile cell smartphone device app touch call text screen notification swipe tap digital wireless portable camera pocket handheld smart'],
  ['⌨','keyboard type input keys computer hardware peripheral qwerty text entry shortcut mechanical switch layout ergonomic wireless backlit keycap coding fast'],
  ['🖱','mouse cursor click point scroll device hardware peripheral navigate input drag select hover right-click wireless optical trackball sensor desktop aim'],
  ['📡','satellite antenna signal dish broadcast communication tower radar network wireless frequency receiver transmit relay orbit space GPS tracking remote data'],
  ['🔌','plug power electric socket connect outlet cable charger cord adapter extension wire prong voltage current supply AC DC unplug jack'],
  ['🔋','battery power charge energy cell electric level full low portable lithium ion rechargeable capacity drain lasting backup reserve indicator percent'],
  ['💾','floppy disk save store data backup memory archive retro old vintage legacy magnetic kilobyte classic obsolete nostalgic icon preservation early'],
  ['💿','disc cd dvd media music optical storage album data burn rom read write laser digital movie audio blu-ray compile rip'],
  ['🖨','printer print output paper copy document hardware office machine ink toner laser inkjet scanner fax page duplex wireless cartridge queue'],
  ['🤖','robot ai machine android bot automated intelligence tech future artificial neural network algorithm learning digital smart assistant chatbot program virtual'],
  ['🧬','dna genetics biology helix science genome cell molecular life strand chromosome gene sequence mutation code evolution heredity protein research biotech'],
  ['⚛','atom science physics nuclear particle element molecule chemistry quantum small electron proton neutron orbit shell energy mass matter fundamental force'],
  // Symbols & status
  ['✅','check done complete yes approved verified success tick confirm pass validate finished accepted cleared accomplished fulfilled satisfied green correct ready'],
  ['❌','cross error wrong no delete cancel reject fail remove block deny invalid prohibited forbidden stop void negate refuse decline close'],
  ['⚠','warning caution alert danger attention risk hazard notice careful issue safety threat vulnerability problem concern flag critical serious urgent watch'],
  ['❓','question mark ask help inquiry unknown uncertain confused what doubt curious wonder clarify explain why how investigate mystery unclear puzzle'],
  ['❗','exclamation important urgent priority attention notice alert emphasis critical vital crucial essential significant pressing immediate required mandatory key necessary serious'],
  ['🔒','lock secure private closed protect restrict safety password encrypted hidden sealed guarded classified confidential shield vault fortress barrier block deny'],
  ['🔓','unlock open public accessible free unrestricted available permission released clear exposed revealed transparent unprotected accessible enabled activated authorized granted'],
  ['🔑','key password access login unlock secret credential enter permission code master skeleton passkey token authentication authorization gateway decode decrypt admit'],
  ['🛡','shield protect security defense guard safe armor barrier firewall ward block prevent resist screen cover insurance warranty backup safeguard anti'],
  ['⚙','gear settings config option preference control configure cog system parameter customize adjust tweak modify setup menu panel dashboard admin tune'],
  ['🔧','wrench tool fix repair adjust maintain tighten utility service spanner mechanic plumber twist socket bolt nut calibrate troubleshoot debug patch'],
  ['🔨','hammer build construct create make forge strike nail tool shape smash break frame assemble craft carpentry blacksmith pound hit mold'],
  ['⚗','flask chemistry lab experiment science potion mix formula brew beaker distill reaction compound solution chemical test analyze concoct alchemy blend'],
  ['🔬','microscope science research examine study magnify biology analysis close detail zoom cell tissue specimen slide laboratory investigate discover observe peer'],
  ['🔭','telescope space astronomy observe stars galaxy universe sky discover far lens optical view distant planet nebula constellation explore cosmos look'],
  ['🧪','test tube experiment science lab sample vial chemistry research trial reagent solution liquid analysis control variable hypothesis verify measure study'],
  ['💎','gem diamond precious jewel crystal brilliant valuable treasure luxury rare sparkle facet carat polished exquisite elite premium gleaming priceless gift values core principles worth'],
  ['💰','money bag rich cash wealth dollar fortune profit savings invest finance gold bank fund income revenue earnings budget capital asset'],
  ['💳','credit card payment bank buy purchase transaction checkout swipe digital debit visa mastercard billing charge account contactless tap wireless pay'],
  ['🏷','label tag price mark category classify organize identify sale metadata name badge sticker barcode product item description attribute sort group'],
  ['🎀','ribbon bow gift decorate present wrap pretty ornament tie loop satin silk festive holiday elegant trim accessory fashion prize award'],
  ['🚩','flag red alert warning danger signal problem marker issue trouble indicator concern suspicious questionable dealbreaker boundary limit caution notice risk'],
  ['🏁','checkered flag finish race end complete final victory lap done goal milestone conclude wrap-up close celebrate achievement culmination terminate last'],
  ['🔶','orange diamond shape icon marker bullet accent highlight geometric bold warm indicator badge status category section divider separator visual symbol'],
  ['🔷','blue diamond shape icon marker bullet accent highlight geometric cool calm indicator badge status category section divider separator visual symbol'],
  ['💠','diamond shape blue dot geometric pattern elegant jewel icon badge ornament decorative crystal sparkle facet precious accent marker indicator logo'],
  ['⬆','arrow up direction rise increase north ascend climb higher above upward elevate lift boost grow promote upgrade advance progress top'],
  ['⬇','arrow down direction fall decrease south descend lower below drop downward sink decline reduce shrink dive plunge collapse scroll bottom'],
  ['➡','arrow right direction forward next proceed east continue advance move onward progress navigate step ahead further transit shift slide push'],
  ['⬅','arrow left direction back previous west return retreat before reverse rewind undo navigate earlier prior behind backward revisit scroll start'],
  ['↩','return back reply undo reverse respond previous revert answer redirect bounce comeback restore recover retry restart react acknowledge loop circle'],
  // Misc useful
  ['🧭','compass navigate direction guide north south east west explore orient bearing heading course waypoint find path route journey travel steer values purpose principles mission vision'],
  ['🗺','map world navigate travel atlas geography route chart explore guide territory region landscape overview plan roadmap terrain survey layout scheme values purpose direction vision'],
  ['📦','box package shipping delivery container cargo parcel product store wrap cardboard seal tape label inventory warehouse logistics supply freight crate'],
  ['🗄','filing cabinet archive storage organize office records drawers department data repository vault preserve catalog backup collection warehouse inventory shelf keep'],
  ['🔐','lock key secure encrypted private protected closed password safe access authentication sealed vault confidential classified restricted guarded fortified cipher hidden'],
  ['📎','paperclip attach fasten bind clip connect hold office document organize staple pin secure bundle group collect gather join link keep'],
  ['✂','scissors cut trim snip crop edit clip divide separate shear slice chop prune carve sever split detach craft paper fabric'],
  ['🖊','pen write edit sign note author draft compose ink letter ballpoint fountain marker script signature journal diary autograph scribble draw'],
  ['📏','ruler measure length straight edge scale size dimension tool line centimeter inch foot metric millimeter precision guide align draft template'],
  ['🔅','dim brightness low light dark screen quiet soft subtle faint gentle muted toned-down ambient subdued reduced weak pale dusky shade'],
  ['🔆','bright sun light high intensity luminous vivid radiant glow display brilliant dazzling glaring spotlight maximum vibrant strong clear powerful beam'],
  ['♻','recycle sustainability green reuse reduce environment eco circle renew clean conservation waste recovery compost biodegradable renewable earth-friendly carbon footprint zero'],
  ['✔','checkmark done complete approved correct verified valid pass accept tick confirmed affirmative positive cleared settled resolved finished accomplished satisfactory okay'],
  ['➕','plus add increase more extra positive create append new expand include insert extend supplement boost augment attach grow incorporate join'],
  ['➖','minus remove decrease less subtract reduce negative take delete shrink diminish lower cut trim pare exclude withdraw strip contract drop'],
  ['🔄','refresh sync loop reload update cycle rotate repeat restart renew regenerate restore reboot recycle revolve circular continuous ongoing perpetual reset'],
  ['⏩','fast forward skip ahead speed quick advance rapid jump next accelerate hurry rush double-time expedite hasten swift prompt instant leap'],
  ['⏪','rewind back reverse previous return replay undo behind earlier retreat review revisit flashback recall backward retrace restore past history prior'],
  ['⏸','pause stop hold wait break freeze halt rest intermission delay suspend temporary standby timeout hiatus respite cease interrupt defer linger'],
  ['▶','play start begin resume run launch go forward trigger active initiate engage proceed operate execute commence kickoff open activate enable'],
  ['🔀','shuffle random mix scramble reorder rearrange jumble variety change swap chaos unpredictable diverse assorted miscellaneous alternate rotate distribute disperse blend'],
  ['⚖','balance scale justice fair equal weigh measure law court judge decide compare evaluate values ethics morals principles equity rights harmony'],
  ['♾','infinity forever endless eternal unlimited boundless perpetual continuous loop beyond limitless timeless always everlasting immeasurable vast cosmic absolute ultimate constant'],
  ['🪄','magic wand spell enchant wizard cast transform miracle power trick illusion sorcery fantasy mystical supernatural charm conjure abracadabra fairy dream'],
  ['🧙','wizard mage sorcerer witch warlock fantasy spell magic enchant mystical conjure potion robes hat staff supernatural arcane occult mythical legendary person'],
  ['🛠','tools hammer wrench fix repair build maintain service kit utility workshop garage mechanic engineer construct assemble hardware equipment DIY craft'],
  ['🪶','feather light write quill bird soft gentle pen airy delicate float breeze wispy plume calligraphy wing nature elegant weightless drift'],
  ['🫧','bubbles soap float pop clean shiny transparent foam light airy sparkle iridescent wash rinse lather playful delicate fragile sphere drift'],
];
