// [emoji, search keywords] — 335 most common/useful emojis
export const EMOJI_PICKER_SET: [string, string][] = [
  // Smileys & emotion
  ['😀','happy smile grin cheerful joy face glad positive mood friendly beam radiant sunny upbeat pleased delighted merry joyful welcome'],
  ['😃','happy smile open mouth glad cheerful joy grin excited sunny bright delighted warm positive friendly enthusiastic pleased eager'],
  ['😄','happy smile grin eyes closed cheerful laugh joy warm pleased beaming delighted sunny upbeat friendly positive merry blissful'],
  ['😁','grin teeth smile happy beaming cheerful wide joy pleased thrilled ecstatic radiant elated merry upbeat bright glad cheeky'],
  ['😆','laugh squint smile happy amused giggle funny joy grin tease hilarious crack-up tickled giddy silly gleeful playful snicker'],
  ['😅','sweat nervous laugh awkward oops relief uncomfortable embarrassed tense uneasy sheepish cringe clumsy mistake blunder flustered phew'],
  ['🤣','rofl rolling floor laugh hilarious crying tears funny comedy hysterical cracking dying priceless ridiculous absurd witty belly-laugh'],
  ['😂','laugh cry funny joy hilarious tears humor lol rofl comedy joke witty giggle hysterical amused cracking dying wheeze'],
  ['🙂','slight smile subtle calm neutral polite soft gentle okay fine friendly pleasant composed serene content steady mild'],
  ['🙃','upside down ironic sarcastic silly goofy playful quirky awkward passive-aggressive subtle dry humor weird odd strange twisted'],
  ['😉','wink flirt playful hint nudge cheeky suggestive knowing sly tease clever fun secret inside-joke confident witty complicit'],
  ['😊','smile blush happy warm kind gentle pleased soft sweet content gracious tender heartfelt lovely appreciative humble grateful'],
  ['😇','halo angel innocent pure good blessed holy kind sweet divine virtuous righteous saintly wholesome moral gracious benevolent'],
  ['🥰','love hearts face adore affection smitten warm sweet romantic tender caring cherish fond devoted hearts smile cuddly'],
  ['😍','heart eyes love adore crush smitten romance infatuated affection desire obsessed gorgeous beautiful attraction swoon stunning captivated'],
  ['🤩','star eyes excited amazed wow awesome thrilled dazzled impressed wonderful starstruck spectacular astonished admire fabulous blown-away'],
  ['😘','kiss wink love blow-kiss flirt romantic affection smooch sweet cute adore heart tender caring fond darling xoxo'],
  ['😋','yum delicious tasty food tongue lick hungry savoring mmm scrumptious appetizing mouthwatering flavor treat enjoy eat crave'],
  ['😛','tongue out playful silly tease goofy childish cheeky fun naughty prankish impish mischievous taunt raspberry jest blep'],
  ['😜','wink tongue crazy silly goofy playful wild zany fun nutty wacky joking mischievous prankish impish tease goof'],
  ['🤪','zany crazy wild goofy silly wacky bonkers loopy nutty eccentric weird bizarre chaotic unhinged hyper manic unhinged'],
  ['🥲','tear smile grateful bittersweet touched moved emotional proud nostalgia sentimental poignant wistful tender heartfelt relieved endearing'],
  ['😎','cool sunglasses chill confident swagger smooth boss relaxed suave laid-back casual stylish composed unfazed nonchalant slick'],
  ['🤔','thinking hmm wondering ponder curious consider question reflect contemplate uncertain puzzled deliberate evaluate analyze skeptical mull'],
  ['🤭','hand over mouth giggle oops shy tee-hee secret whisper suppress blush coy embarrassed cover discreet quiet snicker'],
  ['😏','smirk sly sneaky mischievous cocky flirty knowing cheeky devious suggestive cunning wily crafty scheming playful insinuate'],
  ['😒','unamused annoyed bored displeased unimpressed meh whatever sigh dissatisfied grumpy moody indifferent bland sulky flat uninterested'],
  ['🙄','eye roll annoyed exasperated whatever bored unimpressed dismissive sigh frustrated impatient skeptical sarcastic done tired fed-up'],
  ['😬','grimace awkward cringe nervous uncomfortable yikes tense forced-smile embarrassed wince teeth oops painful strained weird sorry'],
  ['😢','cry sad tear upset weep sorrow grief heartbreak melancholy dejected mournful gloomy downcast depressed dismal lonely'],
  ['😭','bawl sobbing crying loudly wailing devastated heartbroken distraught miserable anguished crushed broken inconsolable tears streaming flood'],
  ['😤','angry huff frustrated mad annoyed furious rage irritated steam vent livid pissed irate seething hostile fume'],
  ['😡','rage angry red furious livid enraged irate seething hostile aggressive fierce wrathful incensed outraged infuriated mad'],
  ['😱','scream shock horror terrified scared afraid panic frightened aghast appalled dread alarmed startled petrified gasp fear'],
  ['😷','mask sick ill medical health cold flu virus disease protect germ bacteria infection quarantine hygiene face covid'],
  ['🤢','nausea sick disgusted gross vomit queasy ill unwell green revolted repulsed stomach yuck nauseated awful repelled'],
  ['🤮','vomit sick puke throw-up nausea disgusted ill gross revolted repulsed horrible awful terrible stomach hurl retch'],
  ['🥳','party celebrate birthday confetti festive hooray cheers congratulations bash jubilant revelry toast fiesta gala carnival woohoo'],
  ['😴','sleep tired zzz rest nap drowsy snore exhausted bedtime dream doze slumber fatigue weary drained snooze'],
  ['🤯','mind blown explode shock amazed unbelievable crazy insane astonished stunned flabbergasted revelation epiphany incredible speechless wow'],
  ['🥶','cold freezing frozen ice chill winter arctic frigid frost shiver numb blue pale glacial hypothermia brr'],
  ['🥵','hot burning sweating overheated heatstroke fever warm summer fire boiling scorching sweltering flushed tropical steaming heat'],
  ['🤠','cowboy hat western rodeo country ranch yeehaw howdy sheriff outlaw frontier prairie wild-west southern rootin texas'],
  ['🥸','disguise incognito fake glasses nose mustache undercover hidden spy stealth anonymous covert secret identity camouflage sneaky'],
  ['🤓','nerd glasses geek smart studious bookworm intellectual brainy academic dorky scholarly learner tech savvy knowledge school'],
  ['😈','devil horns mischief evil naughty wicked imp demon sly trouble sinister dark villain scheming devious purple'],
  ['💀','skull dead death skeleton bones danger toxic fatal lethal deadly mortal doom rip grave cemetery spooky'],
  ['💩','poop crap shit funny gross stinky joke silly brown turd feces waste humor ridiculous absurd pile'],
  ['👻','ghost boo spooky halloween spirit haunted phantom specter paranormal supernatural creepy eerie scary spectral soul casper'],
  ['👽','alien ufo extraterrestrial space martian outer-space sci-fi cosmic foreign strange unknown mysterious otherworldly invader green'],
  ['🙈','see no evil monkey shy embarrassed hide cover-eyes peek awkward blush ashamed facepalm cringe oops cannot-look'],
  ['🫡','salute respect honor duty serve acknowledge formal military tribute obey discipline officer rank attention report sir'],
  ['🫠','melting face relax dissolve hot overwhelmed sinking droopy fading soft warm liquid puddle embarrassed shy swooning'],
  ['🤗','hug open arms warm embrace friendly welcoming cuddle comfort caring affection squeeze support reassure tender hold'],
  ['🥺','pleading puppy eyes cute beg adorable sad sweet hopeful tender vulnerable earnest innocent desperate longing please'],
  // People & gestures
  ['👋','wave hello bye greet farewell welcome hand gesture hi howdy salute morning evening introduction meet ciao'],
  ['👍','thumbs up good ok approve agree yes like correct positive nice affirm endorse validate confirm great'],
  ['👎','thumbs down bad dislike disagree disapprove reject no wrong negative fail oppose deny veto decline boo'],
  ['✌','victory peace sign two win triumph freedom success hand gesture symbol harmony accord truce unity fingers'],
  ['🤝','handshake deal agree partnership cooperation trust alliance meet business contract negotiate collaborate unite pact mutual welcome'],
  ['🙏','pray thanks please beg hope grateful faith worship request mercy namaste appreciate blessing reverence devotion thankful'],
  ['💪','muscle strong flex power strength gym workout fitness bicep tough mighty robust endurance athletic vigor motivation determination grit'],
  ['👁','eye watch see look observe view gaze stare vision focus monitor witness scan survey inspect sight'],
  ['🧠','brain mind think smart intelligent idea genius memory knowledge wisdom logic reason cognitive mental intellect second-brain PKM obsidian clever'],
  ['💋','kiss lips love smooch romance affection peck mouth red lipstick passion desire intimate sweet tender xoxo'],
  ['❤','heart love red passion romance care affection warmth valentine devotion adore cherish bond emotion deep feeling'],
  ['🧡','orange heart warm autumn friendly creative energy enthusiasm vibrant playful bold spirited dynamic active lively fall'],
  ['💛','yellow heart bright sunshine happiness friendship optimism gold warm cheerful radiant glowing positive uplifting sunny'],
  ['💚','green heart nature growth health lucky harmony eco fresh organic renewal vitality balance wellness prosperity earth'],
  ['💙','blue heart calm trust loyalty peace sky ocean serene cool steady reliable sincere depth tranquil true'],
  ['💜','purple heart royal creative mystic spiritual elegant luxury wisdom magic noble regal dreamy enchanting artistic cosmic'],
  ['🖤','black heart dark emo gothic strength power elegant solid formal edgy mysterious deep intense dramatic bold'],
  ['🤍','white heart pure clean innocent simple minimal blank pale clarity transparent pristine fresh light serene snow'],
  ['🩷','pink heart cute sweet soft blush feminine gentle tender lovely romantic charming adorable pastel warm pretty'],
  ['💯','hundred perfect score full complete flawless excellent top maximum best ultimate absolute total agree facts legit'],
  ['💥','boom explosion crash bang impact collision burst blast pow strike hit smash destroy powerful shatter kaboom'],
  ['👀','eyes look watch stare peek curious observe glance spy attention gaze scan notice perceive scrutinize peep'],
  ['🫶','heart hands love care support appreciate cherish grateful adore affection embrace nurture compassion tenderness kindness'],
  ['👏','clap applause bravo congratulations well done praise celebrate cheer ovation encore standing recognition honor kudos'],
  ['🤞','fingers crossed luck hope wish fortune faith prayer promise desire optimism chance gamble bet superstition please'],
  ['✍','writing hand author compose draft pen pencil scribe letter note journal diary manuscript essay creative note-taking daily write'],
  ['🦾','mechanical arm prosthetic robot strong bionic power tech future cyborg augmented enhanced titanium steel advanced upgrade'],
  // Nature & animals
  ['🌱','seedling sprout grow plant garden green fresh new beginning growth nurture cultivate develop emerge start motivation habit progress'],
  ['🌿','herb leaf green nature botanical plant garden organic fresh foliage verdant lush tropical fern frond branch herb'],
  ['🍀','clover luck lucky fortune shamrock irish four leaf charm green blessing chance auspicious favorable prosperity wish'],
  ['🌸','blossom flower pink cherry spring japan sakura bloom petal delicate fragile beauty grace renewal feminine soft'],
  ['🌹','rose flower red love romance valentine beautiful elegant garden fragrant classic thorns bouquet gift passion beauty'],
  ['🌺','flower hibiscus tropical bloom garden colorful blossom hawaii red petal exotic warm paradise island vibrant lush'],
  ['🌻','sunflower bright yellow sun summer garden happy cheerful bloom warm golden tall field radiant joyful cheerful'],
  ['🌼','daisy flower blossom yellow white garden spring bloom petal field wildflower cheerful bright fresh innocent pure'],
  ['🌷','tulip flower spring garden bloom pink colorful petal elegant bulb dutch holland fragrant vase bouquet pretty'],
  ['💐','bouquet flowers gift arrangement bunch present celebration congratulations wedding anniversary valentine romantic beautiful colorful floral bundle'],
  ['🥀','wilted flower dead dying sad drooping fading withered loss decay end goodbye farewell grief heartbreak wilt'],
  ['🌾','rice grain wheat harvest crop farm agriculture field cereal stalk golden autumn ripe rural country paddy'],
  ['🍂','autumn fall leaf season brown orange harvest change dry maple deciduous crisp golden rustic nostalgic wind'],
  ['🌊','wave ocean water sea surf tide beach coast marine splash current deep blue shore nautical swell'],
  ['🔥','fire flame hot burn heat lit trending popular blazing passion fierce intense energy wild warm motivation drive hustle'],
  ['❄','snowflake cold ice winter frozen frost chill freeze crystal snow unique delicate white pure arctic flurry'],
  ['⚡','lightning bolt energy power electric thunder fast speed charge shock voltage surge zap current intensity flash'],
  ['🌈','rainbow colors spectrum hope promise diversity pride arch weather sky after-rain bridge multicolor vivid bright beautiful'],
  ['☀','sun sunny bright day warm light summer morning golden clear radiant dawn daylight sunshine noon hot'],
  ['🌞','sun face sunny bright warm cheerful happy smile golden radiant day morning summer glow beaming friendly'],
  ['🌅','sunrise morning dawn new-day horizon ocean beach golden light hope beginning fresh start early wake beautiful'],
  ['🌙','moon night crescent dark sky evening sleep lunar celestial twilight midnight dream nocturnal dusk starlit glow'],
  ['⭐','star favorite rated best top quality night sky shining bright golden award featured highlight bookmark motivation aspiration goal wish'],
  ['🌟','glowing star shine brilliant sparkle twinkle radiant celestial bright excellent dazzling luminous stellar magnificent outstanding'],
  ['✨','sparkles shine magic glitter glamour special clean new fresh dazzle enchant fairy dust twinkling glowing premium'],
  ['🌌','galaxy milky-way night sky stars space cosmos universe nebula celestial dark vast deep astral constellation cosmic'],
  ['🌠','shooting star wish meteor night sky falling space celestial dream hope luck comet trail streak magical'],
  ['🏔','mountain peak summit high adventure nature hike climb snow alpine majestic rugged wilderness terrain elevation'],
  ['🌍','earth globe world planet geography international travel map continent environment global humanity civilization ecosystem terra'],
  ['🌐','globe internet web network worldwide connected online digital global browser domain website cyberspace virtual cloud'],
  ['🪴','potted plant house indoor green decor home garden succulent grow ceramic shelf desk room windowsill cozy'],
  ['🌲','evergreen tree pine forest nature wood christmas conifer green tall spruce fir woodland timber grove dense'],
  ['🍄','mushroom fungus forest nature wild toadstool organic earthy woodland magic mycelium cap stem spore fairy'],
  ['🐝','bee honey buzz insect pollinate hive sting yellow worker busy queen colony flower nectar wax sweet'],
  ['🦋','butterfly insect nature beautiful transform wings colorful metamorphosis garden flutter cocoon caterpillar chrysalis elegant change'],
  ['🐾','paw prints animal pet footprint track dog cat walk trail path follow clue trace mark step'],
  ['🐱','cat kitten pet feline meow cute furry animal whiskers playful independent curious agile pounce purr neko'],
  ['🐶','dog puppy pet canine bark loyal cute furry animal friend faithful companion fetch walk tail woof'],
  ['🐦','bird tweet chirp fly wing feather animal nature sky perch nest song sparrow finch robin singing'],
  ['🦅','eagle bird raptor fly soar majestic predator wing sky freedom hunt prey powerful wild america'],
  ['🐧','penguin bird cold ice arctic antarctic animal cute waddle tuxedo swim fish emperor colony winter'],
  ['🦉','owl bird night wise nocturnal hoot wisdom animal forest eye feather silent hunt branch moon'],
  ['🦜','parrot bird colorful tropical talk mimic pet feather fly beak wing exotic jungle rainforest macaw'],
  ['🕊️','dove bird peace white fly gentle wing olive branch freedom hope calm pure spirit symbol harmony'],
  ['🐸','frog toad green amphibian ribbit hop leap pond swamp lily-pad croak nature wet slimy cute kermit'],
  ['🐢','turtle tortoise slow shell reptile steady patient calm nature ocean sea wise old ancient zen relaxed'],
  ['🐍','snake serpent reptile slither hiss venom coil danger wild nature python cobra viper scales sneaky'],
  ['🦊','fox clever cunning sly orange animal cute wild forest smart trickster woodland brush tail red foxy'],
  ['🐻','bear animal brown grizzly forest wild nature strong hibernate cub furry woodland powerful fierce honey'],
  ['🐼','panda bear black white bamboo china cute animal endangered fluffy gentle adorable zoo peaceful calm cuddly'],
  ['🦁','lion king jungle cat wild animal brave fierce pride mane roar savanna powerful majestic royal leader'],
  ['🐯','tiger cat stripes wild animal fierce powerful jungle predator orange strong bold ferocious beast prowl'],
  ['🐒','monkey primate ape animal playful jungle tree banana climbing funny curious mischievous wild swing silly'],
  ['🐙','octopus tentacle sea ocean marine animal squid deep underwater intelligent camouflage suction cephalopod eight'],
  ['🐚','shell seashell beach ocean sea shore conch spiral sand marine nature coastal pearl collect tide souvenir'],
  ['🐠','tropical fish colorful ocean sea marine reef aquarium underwater coral nemo bright exotic animal swim'],
  ['🐬','dolphin ocean sea marine mammal swim jump playful intelligent friendly coastal wave tropical aquatic smart'],
  ['🐳','whale ocean sea marine mammal huge deep water blowhole humpback blue giant majestic nature spout'],
  // Food & drink
  ['☕','coffee tea hot drink cup morning cafe latte espresso brew cappuccino java bean roast aroma wake'],
  ['🍵','tea cup hot drink matcha green herbal warm sip beverage chamomile jasmine oolong steep kettle zen'],
  ['🍺','beer drink pub bar cheers alcohol lager ale mug cold draft brew hops craft stout pint'],
  ['🍎','apple fruit red healthy food snack organic teacher crisp fresh juicy sweet autumn harvest orchard natural'],
  ['🍋','lemon yellow sour citrus fresh juice zest tart tangy squeeze vitamin acidic bright peel slice lime'],
  ['🍇','grapes fruit wine purple vine bunch cluster vineyard harvest juice raisin sweet dessert snack bunch'],
  ['🍉','watermelon fruit summer red green seeds juicy sweet refreshing slice picnic tropical melon cool hydrate'],
  ['🍊','orange tangerine citrus fruit juice vitamin fresh sweet round peel segment tropical mandarin clementine zest'],
  ['🍌','banana fruit yellow tropical peel sweet potassium healthy snack smoothie split monkey bunch ripe creamy'],
  ['🍓','strawberry fruit red berry sweet juicy dessert jam fresh garden summer shortcake smoothie organic pick'],
  ['🍑','peach fruit sweet fuzzy pit stone juicy soft pink summer ripe nectarine cobbler pie emoji'],
  ['🥭','mango fruit tropical sweet juicy exotic orange yellow smoothie ripe fresh dessert summer asian lassi'],
  ['🥝','kiwi fruit green fuzzy tropical vitamin fresh sweet tangy exotic healthy smoothie slice small tart'],
  ['🍒','cherry fruit red pair sweet dessert pie stem small round ripe tart berry summer twin'],
  ['🥑','avocado healthy green food guacamole fresh organic toast salad superfood nutrition fat creamy ripe spread'],
  ['🌰','chestnut nut seed brown autumn fall roast warm acorn walnut hazelnut harvest tree nature shell kernel'],
  ['🍝','pasta spaghetti noodle italian food dinner sauce tomato meatball linguine fettuccine carbonara bolognese recipe cook meal carbs'],
  ['🍕','pizza food slice italian cheese pepperoni dinner lunch meal party takeout delivery crust topping margherita'],
  ['🍔','burger hamburger food fast-food beef bun patty cheese grill bbq lunch dinner meal american fries'],
  ['🌮','taco mexican food shell beef chicken lettuce cheese salsa tortilla dinner lunch spicy tex-mex tuesday'],
  ['🍣','sushi japanese food rice fish salmon tuna roll maki nigiri raw seafood wasabi ginger chopsticks'],
  ['🍜','noodle ramen soup bowl asian japanese pho broth hot steaming chopsticks warm comfort food slurp'],
  ['🍩','donut doughnut sweet dessert sprinkles icing glaze pastry breakfast treat bakery sugar frosted ring hole glazed'],
  ['🍪','cookie biscuit sweet snack chocolate chip dessert bake treat crumble crispy buttery batch oven crunch'],
  ['🍫','chocolate bar sweet candy cocoa dark milk dessert treat snack confection fudge ganache cacao brown'],
  ['🍬','candy sweet wrapper treat sugar confection hard lollipop caramel toffee butterscotch bonbon taffy colorful'],
  ['🎂','cake birthday celebration dessert sweet party frosting candle treat slice chocolate vanilla cream layers wish'],
  ['🍰','shortcake slice dessert sweet cream berry strawberry cheesecake pastry treat piece portion bakery tiramisu'],
  ['🧁','cupcake sweet dessert treat frosting bake mini cake sprinkles sugar icing butter cream vanilla pretty'],
  ['🍦','ice cream cone dessert sweet frozen summer vanilla chocolate scoop treat cool soft-serve gelato waffle'],
  ['🍷','wine glass drink red white elegant dinner celebration grape toast vineyard vintage merlot chardonnay pour'],
  ['🍯','honey jar sweet golden bee nectar syrup sticky natural amber drizzle comb pure organic pooh'],
  // Activities & sports
  ['🎯','target bullseye goal aim focus precision objective hit center shoot accuracy direct purpose mission intent strategy plan motivation OKR productivity dart'],
  ['🏆','trophy award win champion success prize competition gold medal achieve glory honor excellence triumph motivation milestone cup'],
  ['🥇','medal gold first winner champion award best victory prize compete podium top achievement record olympic'],
  ['🥈','medal silver second place runner-up award competition podium honor prize achievement excellent strong effort'],
  ['🥉','medal bronze third place award competition podium honor prize achievement good effort solid worthy try'],
  ['🎮','game controller play video console gaming joystick fun arcade entertain pixel level score quest adventure videogame computer'],
  ['🕹','joystick arcade retro game controller play classic vintage gaming old-school pixel cabinet button lever stick'],
  ['🎨','art palette creative paint colors draw design brush canvas studio illustration sketch masterpiece gallery museum'],
  ['🎵','music note song melody tune sound rhythm beat listen audio harmony instrument compose lyric chorus sing'],
  ['🎬','clapper film movie cinema director action scene video cut shoot production camera reel premiere oscar'],
  ['📷','camera photo picture snap capture image shoot lens portrait memory digital photography focus exposure selfie'],
  ['🎁','gift present box surprise birthday wrap holiday bow giving package reward treat donation offering christmas'],
  ['🎲','dice game random roll chance luck board casino gamble play probability bet wager odds risk number'],
  ['🧩','puzzle piece solve jigsaw fit connect challenge logic brain together assemble pattern match complete think'],
  ['🎭','theater masks drama comedy tragedy acting perform stage show play musical opera scene character broadway'],
  ['🏃','running exercise fitness jog sprint athlete sport race training track marathon cardio endurance speed fast'],
  ['🚶','walking walk stroll hike pedestrian step person pace wander roam amble stride commute foot path leisurely'],
  ['🧘','yoga meditation calm relax zen mindful stretch balance pose peace breathe serenity harmony wellness center'],
  ['🎸','guitar music rock instrument band play strings chord acoustic electric solo riff strum amplifier jam'],
  ['🎤','microphone sing voice karaoke record perform speak audio vocal stage broadcast interview podcast speech'],
  ['🎧','headphones music listen audio sound beats wireless over-ear podcast stereo noise-cancel bass volume zone'],
  ['⚽','soccer football ball sport kick goal field match team game play pitch league tournament world-cup'],
  ['🏀','basketball ball sport hoop court shoot dunk game team play dribble slam match league nba'],
  ['🎾','tennis ball racket sport court game match serve volley ace set tournament rally net wimbledon'],
  // Travel & places
  ['🚀','rocket launch space shuttle blast explore mission fast speed orbit astronaut cosmos takeoff motivation ambition productivity moon'],
  ['✈','airplane travel fly flight jet trip journey airline departure sky arrival boarding runway pilot vacation'],
  ['🚂','train travel rail transport commute locomotive station track journey ride railway express schedule platform steam'],
  ['🏠','house home building family residence living shelter comfort cozy dwelling roof neighborhood street property safe'],
  ['🏫','school education building class study learn teach university college campus academy institution classroom student homework'],
  ['🏢','office building work corporate business tower downtown company workplace headquarters block urban professional city job'],
  ['🏥','hospital medical health building clinic doctor care emergency room treatment medicine patient ward heal nurse'],
  ['🏰','castle fortress palace medieval royal kingdom tower keep moat wall stone historic fairy-tale kingdom princess'],
  ['🏪','store shop convenience retail buy market local mini-mart business front awning sell goods supply corner'],
  ['🏙','city building skyline urban downtown skyscraper metro architecture towers busy modern concrete landscape panorama view'],
  ['🌆','city sunset evening skyline dusk twilight urban golden horizon vista panorama silhouette beautiful glow warm'],
  ['🌃','night city stars urban skyline dark evening lights downtown buildings starry midnight metropolitan late neon'],
  ['🗼','tower landmark tokyo tall structure monument observation antenna tourist famous iconic viewpoint skyline spire beacon'],
  ['🏖','beach vacation holiday sand sun relax coast tropical resort shore umbrella palm waves swim paradise'],
  ['⛺','tent camping outdoor adventure nature camp hike shelter wilderness trek bonfire campfire forest park survival'],
  // Objects & tools
  ['📁','folder directory organize files storage category archive system group contain collection structure project classify manage'],
  ['📂','open folder browse directory files explore access documents content view expand reveal display inside look'],
  ['📄','document page file text paper sheet blank note report form letter article template draft print'],
  ['📝','memo write note edit pencil draft compose jot pad paper journal entry log record note-taking productivity PKM obsidian daily plan'],
  ['📋','clipboard copy paste checklist list tasks form survey record data inventory register project management kanban workflow productivity board'],
  ['📓','notebook journal diary daily log planner note-taking writing personal reflection thoughts record entry ledger bound'],
  ['📒','ledger notebook yellow note-taking planner log record register journal study workbook pad bound memo handbook'],
  ['🗒','notepad spiral memo notes jot scratch paper quick draft scribble bullet list to-do reminder tear'],
  ['📌','pushpin pin tack mark attach fixed bulletin board location hold sticky notice important remember highlight'],
  ['📍','location pin map marker place navigate address point destination drop waypoint coordinate GPS venue spot'],
  ['🔖','bookmark save mark tag favorite label chapter placeholder remember keep flag reference highlight annotate later'],
  ['🗂','index dividers tabs organize sort category section file cabinet group partition separate classify second-brain PKM knowledge-base taxonomy'],
  ['📅','calendar date schedule plan event day month year appointment agenda booking diary timeline deadline project management planner productivity week'],
  ['🗓','calendar spiral planner monthly schedule organize dates agenda timeline view weekly annual overview layout display'],
  ['⏰','alarm clock time wake morning schedule reminder urgent prompt early ring buzzer alert snooze set punctual'],
  ['🕐','clock time hour watch schedule deadline countdown moment period tick minute second duration interval pace'],
  ['⏱','stopwatch timer speed race countdown track measure performance seconds lap interval benchmark timing record split'],
  ['📊','chart bar data statistics graph analytics metrics report visual compare dashboard insight trend analysis KPI project management score'],
  ['📈','chart up growth trend increase rise profit improve progress gain ascend upward boost expand rally'],
  ['📉','chart down decline fall drop decrease loss reduce crash lower slump downturn plunge shrink dip'],
  ['💡','idea light bulb insight inspiration bright creative solution innovation tip eureka invention brainstorm thought motivation productivity spark'],
  ['🔍','search magnify zoom find discover look investigate inspect explore detail examine research scan probe lens'],
  ['🔗','link chain url connect web hyperlink attach join bond reference anchor association PKM backlink graph share'],
  ['📢','loudspeaker announce broadcast megaphone alert proclamation notify shout public news declaration publicity promote campaign'],
  ['🔔','bell notification alert ring alarm remind chime ding attention sound signal update notice ping subscribe'],
  ['💬','speech bubble chat message talk communicate discuss conversation text dialog comment reply respond thread forum'],
  ['💭','thought think bubble idea ponder dream imagine reflect wonder muse daydream consider fantasy vision cloud'],
  ['📚','books study library read learn education knowledge stack collection reference textbook academic literature shelf reading-list second-brain school'],
  ['📖','open book read learn study page text knowledge literature chapter story novel tale passage journal diary reading daily log'],
  ['📜','scroll document ancient paper certificate decree parchment history old formal diploma charter proclamation manuscript'],
  ['✉','envelope email letter mail postal message inbox correspondence send post stamp seal deliver package address'],
  ['📧','email message digital mail compose inbox outbox electronic send receive newsletter subscribe forward reply thread'],
  ['📥','inbox download receive import collect arrive gather incoming tray message queue pending unread new items'],
  ['📤','outbox upload send export share publish dispatch deliver release submit broadcast distribute deploy push ship'],
  ['🗑','trash delete remove waste garbage bin discard throw dispose recycle junk refuse clean purge erase'],
  ['📐','triangle ruler geometry math angle measure draft technical precision shape protractor degree architect blueprint'],
  ['📏','ruler measure length straight edge scale size dimension tool line centimeter inch foot metric distance'],
  ['✏','pencil write draw edit sketch lead yellow school art draft note homework study sharp HB graphite doodle'],
  ['🖋','fountain pen write ink elegant calligraphy sign formal letter script cursive nib classic autograph premium'],
  ['🖊','pen write edit sign note author draft compose ink letter ballpoint marker script signature document'],
  ['🧲','magnet attract pull force iron metal charge stick pole draw repel field north south horseshoe'],
  ['💊','pill medicine health pharmacy drug capsule vitamin dose cure treatment prescription supplement tablet remedy'],
  ['🩺','stethoscope doctor health medical exam checkup hospital clinical care heart listen diagnosis nurse physician'],
  ['🪞','mirror reflection look glass vanity self image surface shine check inspect reverse symmetry identity'],
  ['🧸','teddy bear toy cute stuffed plush child soft comfort cuddly huggable sweet innocent play nursery'],
  // Tech
  ['💻','laptop computer code program work device screen technology notebook portable developer software engineer terminal typing'],
  ['🖥','desktop monitor screen display computer workstation setup office technology pc tower dual ultrawide resolution'],
  ['📱','phone mobile cell smartphone device app touch call text screen notification swipe tap digital pocket'],
  ['⌨','keyboard type input keys computer hardware peripheral qwerty text entry shortcut mechanical switch layout coding'],
  ['🖱','mouse cursor click point scroll device hardware peripheral navigate input drag select hover right-click wireless'],
  ['📡','satellite antenna signal dish broadcast communication tower radar network wireless frequency receiver transmit relay'],
  ['🔌','plug power electric socket connect outlet cable charger cord adapter extension wire prong voltage charge'],
  ['🔋','battery power charge energy cell electric level full low portable lithium ion rechargeable capacity drain'],
  ['💾','floppy disk save store data backup memory archive retro old vintage legacy magnetic kilobyte classic'],
  ['💿','disc cd dvd media music optical storage album data burn rom read write laser digital movie'],
  ['🖨','printer print output paper copy document hardware office machine ink toner laser inkjet scanner fax'],
  ['🤖','robot ai machine android bot automated intelligence tech future artificial neural network algorithm learning chatbot'],
  ['🧬','dna genetics biology helix science genome cell molecular life strand chromosome gene sequence mutation biotech'],
  ['⚛','atom science physics nuclear particle element molecule chemistry quantum small electron proton neutron orbit fundamental'],
  // Symbols & status
  ['✅','check done complete yes approved verified success tick confirm pass validate finished accepted cleared ready'],
  ['❌','cross error wrong no delete cancel reject fail remove block deny invalid prohibited forbidden stop'],
  ['⚠','warning caution alert danger attention risk hazard notice careful issue safety threat vulnerability problem critical'],
  ['❓','question mark ask help inquiry unknown uncertain confused what doubt curious wonder clarify explain why'],
  ['❗','exclamation important urgent priority attention notice alert emphasis critical vital crucial essential significant pressing'],
  ['🔒','lock secure private closed protect restrict safety password encrypted hidden sealed guarded classified secret'],
  ['🔓','unlock open public accessible free unrestricted available permission released clear exposed revealed transparent granted'],
  ['🔑','key password access login unlock secret credential enter permission code master skeleton passkey token auth'],
  ['🛡','shield protect security defense guard safe armor barrier firewall ward block prevent resist screen cover'],
  ['⚙','gear settings config option preference control configure cog system parameter customize adjust tweak modify admin'],
  ['🔧','wrench tool fix repair adjust maintain tighten utility service spanner mechanic plumber twist socket tune'],
  ['🔨','hammer build construct create make forge strike nail tool shape smash break frame assemble craft'],
  ['⚗','flask chemistry lab experiment science potion mix formula brew beaker distill reaction compound solution alchemy'],
  ['🔬','microscope science research examine study magnify biology analysis close detail zoom cell tissue specimen lab'],
  ['🔭','telescope space astronomy observe stars galaxy universe sky discover far lens optical view distant cosmos'],
  ['🧪','test tube experiment science lab sample vial chemistry research trial reagent solution liquid analysis test'],
  ['💎','gem diamond precious jewel crystal brilliant valuable treasure luxury rare sparkle facet carat polished values core principles quality'],
  ['💰','money bag rich cash wealth dollar fortune profit savings invest finance gold bank fund income budget'],
  ['💳','credit card payment bank buy purchase transaction checkout swipe digital debit visa mastercard billing pay'],
  ['🏷','label tag price mark category classify organize identify sale metadata name badge sticker barcode product'],
  ['🎀','ribbon bow gift decorate present wrap pretty ornament tie loop satin silk festive holiday cute'],
  ['🚩','flag red alert warning danger signal problem marker issue trouble indicator concern suspicious questionable deal-breaker'],
  ['🏁','checkered flag finish race end complete final victory lap done goal milestone conclude wrap-up sprint'],
  ['🔴','red circle dot stop error danger alert color marker bullet indicator badge status symbol active'],
  ['🟠','orange circle dot color marker warm autumn indicator badge status bullet accent symbol highlight amber'],
  ['🟡','yellow circle dot color marker bright caution indicator badge status bullet accent gold sunshine pending'],
  ['🟢','green circle dot go success active ok online color marker indicator badge status live ready'],
  ['🔵','blue circle dot color marker calm cool indicator badge status bullet accent symbol primary info'],
  ['🟣','purple circle dot color marker violet creative indicator badge status bullet accent symbol royal premium'],
  ['⚫','black circle dot dark color marker indicator badge status bullet strong bold minimal symbol filled'],
  ['⚪','white circle dot light color marker indicator badge status bullet clean minimal empty blank hollow'],
  ['🔶','orange diamond shape icon marker bullet accent highlight geometric bold warm indicator badge status large'],
  ['🔷','blue diamond shape icon marker bullet accent highlight geometric cool calm indicator badge status large'],
  ['💠','diamond shape blue dot geometric pattern elegant jewel icon badge ornament decorative crystal sparkle small'],
  ['⬆','arrow up direction rise increase north ascend climb higher above upward elevate lift boost grow'],
  ['⬇','arrow down direction fall decrease south descend lower below drop downward sink decline reduce dig'],
  ['➡','arrow right direction forward next proceed east continue advance move onward progress navigate step go'],
  ['⬅','arrow left direction back previous west return retreat before reverse rewind undo navigate earlier behind'],
  ['↩','return back reply undo reverse respond previous revert answer redirect bounce comeback restore recover loop'],
  // Misc useful
  ['🧭','compass navigate direction guide north south east west explore orient bearing heading course waypoint values purpose mission vision moral'],
  ['🗺','map world navigate travel atlas geography route chart explore guide territory region roadmap plan direction vision overview'],
  ['📦','box package shipping delivery container cargo parcel product store wrap cardboard seal tape label inventory crate'],
  ['🗄','filing cabinet archive storage organize office records drawers department data repository vault preserve catalog backup'],
  ['🔐','lock key secure encrypted private protected closed password safe access authentication sealed vault classified hidden'],
  ['📎','paperclip attach fasten bind clip connect hold office document organize staple pin secure bundle link'],
  ['✂','scissors cut trim snip crop edit clip divide separate shear slice chop prune carve sever craft'],
  ['🔅','dim brightness low light dark screen quiet soft subtle faint gentle muted toned-down ambient night'],
  ['🔆','bright sun light high intensity luminous vivid radiant glow display brilliant dazzling glaring spotlight max'],
  ['♻','recycle sustainability green reuse reduce environment eco circle renew clean conservation waste recovery compost earth'],
  ['✔','checkmark done complete approved correct verified valid pass accept tick confirmed affirmative positive cleared yes'],
  ['➕','plus add increase more extra positive create append new expand include insert extend supplement grow'],
  ['➖','minus remove decrease less subtract reduce negative take delete shrink diminish lower cut trim drop'],
  ['🔄','refresh sync loop reload update cycle rotate repeat restart renew regenerate restore reboot recycle retry'],
  ['⏩','fast forward skip ahead speed quick advance rapid jump next accelerate hurry rush double-time swift'],
  ['⏪','rewind back reverse previous return replay undo behind earlier retreat review revisit flashback recall past'],
  ['⏸','pause stop hold wait break freeze halt rest intermission delay suspend temporary standby timeout breathe'],
  ['▶','play start begin resume run launch go forward trigger active initiate engage proceed operate execute'],
  ['🔀','shuffle random mix scramble reorder rearrange jumble variety change swap chaos unpredictable diverse assorted sort'],
  ['⚖','balance scale justice fair equal weigh measure law court judge decide compare evaluate values equity'],
  ['♾','infinity forever endless eternal unlimited boundless perpetual continuous loop beyond limitless timeless always everlasting'],
  ['🪄','magic wand spell enchant wizard cast transform miracle power trick illusion sorcery fantasy mystical fairy'],
  ['🧙','wizard mage sorcerer witch warlock fantasy spell magic enchant mystical conjure potion robes hat staff'],
  ['🛠','tools hammer wrench fix repair build maintain service kit utility workshop garage mechanic engineer craft'],
  ['🪶','feather light write quill bird soft gentle pen airy delicate float breeze wispy plume calligraphy'],
  ['🫧','bubbles soap float pop clean shiny transparent foam light airy sparkle iridescent wash rinse playful'],
];
